export const characters = [
  {
    id: 'mochi',
    name: 'Mochi',
    short: 'Quietly cheerful',
    detail: 'Your quietly cheerful companion.',
    greeting: 'Mochi is happy to keep you company.',
    quote: 'Small screens. Bigger feelings.',
    pace: 1,
    body: '#f8f3e6',
    face: '#121610',
    blush: '#f4ba9f',
    crease: '#c6b79e',
    accent: '#909e71',
    leaf: '#c9d6ae',
  },
  {
    id: 'sprout',
    name: 'Sprout',
    short: 'Endlessly curious',
    detail: 'A curious little seedling.',
    greeting: 'Sprout is exploring with you.',
    quote: 'Good things start small.',
    pace: 1.08,
    body: '#bce4b4',
    face: '#203a2b',
    blush: '#f2bea0',
    crease: '#79ad7f',
    accent: '#4f9567',
    leaf: '#cdecaa',
  },
  {
    id: 'peach',
    name: 'Peach',
    short: 'A playful sweetheart',
    detail: 'A sweet little cat with a playful streak.',
    greeting: 'Peach has found a cozy spot beside you.',
    quote: 'A little mischief. A lot of heart.',
    pace: 1.16,
    body: '#f7c89f',
    face: '#3b2a24',
    blush: '#ed9e8b',
    crease: '#c79678',
    accent: '#eca595',
    leaf: '#ffe1bd',
  },
  {
    id: 'nimbus',
    name: 'Nimbus',
    short: 'A gentle daydreamer',
    detail: 'A dreamy little cloud.',
    greeting: 'Nimbus is taking it one thought at a time.',
    quote: 'There’s room to take it slow.',
    pace: 0.8,
    body: '#c8dff5',
    face: '#26354a',
    blush: '#d9b7cf',
    crease: '#93afcb',
    accent: '#abc7e5',
    leaf: '#e5f0fc',
  },
] as const;
export type CharacterId = (typeof characters)[number]['id'];
export const characterById = (id: string) => characters.find((c) => c.id === id) ?? characters[0];
